"""Provider-neutral Material Layer contracts."""

from .models import (
    Availability,
    AcquisitionInfo,
    CandidateSource,
    ContinuityRef,
    Coverage,
    CoverageStatus,
    DurationHint,
    ImageNeedSpec,
    VideoNeedSpec,
    VoiceNeedSpec,
    VoiceIdentityRef,
    VoiceIdentitySource,
    BgmNeedSpec,
    SfxNeedSpec,
    FileInfo,
    IntelligenceStatus,
    MaterialAsset,
    MaterialBundle,
    MaterialGap,
    MaterialMatch,
    MaterialNeed,
    MaterialPlan,
    MaterialReadiness,
    MediaType,
    NeedImportance,
    NeedIntent,
    NeedScope,
    NeedScopeType,
    ReadinessStatus,
    RetrievalIntent,
    PreviewInfo,
    SemanticAnnotation,
    SemanticField,
    SemanticInference,
    SemanticInfo,
    RightsEvidence,
    RightsInfo,
    RightsStatus,
    SupplyCandidate,
    SupplyRun,
    SupplySourceResult,
    TechnicalInfo,
    TechnicalStatus,
)

__all__ = [
    "Availability", "AcquisitionInfo", "CandidateSource", "ContinuityRef", "Coverage",
    "CoverageStatus", "DurationHint", "FileInfo", "IntelligenceStatus", "MaterialAsset", "MaterialBundle",
    "ImageNeedSpec", "VideoNeedSpec", "VoiceNeedSpec", "VoiceIdentityRef", "VoiceIdentitySource",
    "BgmNeedSpec", "SfxNeedSpec",
    "MaterialGap", "MaterialMatch", "MaterialNeed", "MaterialPlan",
    "MaterialReadiness", "MediaType", "NeedImportance", "NeedIntent",
    "NeedScope", "NeedScopeType", "ReadinessStatus", "RetrievalIntent",
    "RightsEvidence", "RightsInfo", "RightsStatus", "PreviewInfo", "SemanticAnnotation", "SemanticField",
    "SemanticInference", "SemanticInfo", "SupplyCandidate",
    "SupplyRun", "SupplySourceResult", "TechnicalInfo", "TechnicalStatus",
]
