import assert from 'node:assert/strict';
import { projectCreatorWorkspace as project } from '../src/lib/creatorWorkspace.ts';
const confirmed = { chat_workflow: { proposal_status: 'CONFIRMED' } };
const proposal = project({ chat_workflow: { proposal_status: 'READY_FOR_CONFIRMATION' } }, null, null);
assert.equal(proposal.title, '需要你处理');
assert.equal(proposal.proposal, true);
assert.equal(proposal.pending, 1);
const early = project({ ...confirmed, preparation: { status: 'FAILED', last_error: '内容时长不一致' } }, null, null);
assert.equal(early.failureStage, '内容准备');
assert.equal(early.failureReason, '内容时长不一致');
const selected = project({ ...confirmed, selected_attempt_id: 'a', selected_output_name: 'final', preparation: { status: 'FAILED' } }, { attempt_id: 'a', outputs: { final: {} }, review_status: 'APPROVED' }, null);
assert.equal(selected.state, 'completed');
assert.equal(selected.failureStage, null);
assert.ok(selected.timeline.every(stage => stage.state === 'completed'));
const waitingFee = project(confirmed, { attempt_id: 'a', execution_status: 'NOT_SUBMITTED', plan: { status: 'ready' }, cost: { status: 'pricing_read' }, material_gate: { status: 'MATERIAL_READY' }, material_planning: { status: 'PLANNING_READY' } }, null);
assert.equal(waitingFee.pending, 1);
assert.equal(waitingFee.timeline[4].state, 'action-required');
const uncertain = project(confirmed, { execution_status: 'SUBMISSION_UNCERTAIN', material_gate: { status: 'MATERIAL_READY' } }, null);
assert.equal(uncertain.failureStage, null);
const resumed = project({ ...confirmed, preparation: { status: 'FAILED' } }, { material_planning: { status: 'PLANNING_READY' }, material_gate: { status: 'MATERIAL_NOT_READY', blocking_needs: ['scene-1', 'scene-2'] } }, { claims: [{ status: 'REVIEW_REQUIRED' }] });
assert.equal(resumed.failureStage, null);
assert.equal(resumed.pending, 3);
assert.equal(resumed.timeline[1].state, 'action-required');
assert.equal(resumed.timeline[3].state, 'action-required');
console.log('Creator projection: proposal, early failure, selected output, cost, uncertain submission, resumed gates passed');
